### ISSUE TITLE
Suggestion: Progress Bar

### ISSUE THREAD

**Issue by cjdduarte** [sivenchinniah/Pokemanki#1]
The idea of ​​the addon is very good, but I would like to suggest an improvement where we would see a progress bar on the screen we answered the cards, similar to the addon from [Anki Habidica](https://ankiweb.net/shared/info/1758045507).

![image](https://user-images.githubusercontent.com/42243532/66700151-ea963080-ecc3-11e9-8c30-31d6cf752a51.png)

Just an idea to think about. Congratulations on the addon.

**Comment by sivenchinniah** [comment]
This is a good idea and actually one I was thinking of adding to the next update. I'm not quite sure yet how to incorporate it specifically into the review screen, but I was thinking of having one in the stats screen under the Pokemon to start

**Comment by cjdduarte** [comment]
I proposed on the review screen because it would encourage to keep answering the cards. See what you find most interesting.
