### ISSUE TITLE
Pictures are not showing

### ISSUE THREAD

**Issue by galantra** [sivenchinniah/Pokemanki#2]
This is how my stats screen appears.
![grafik](https://user-images.githubusercontent.com/52420923/67184881-02b53080-f3e5-11e9-83f3-a575b17eaa32.png)

Apart from that, I'm also affected by interference with the add-on "True Retention by Card Maturity" (which someone already stated in the ankiweb reviews). I deactivated it to test Pokemanki.

**Comment by sivenchinniah** [comment]
Yeah I'm hoping to find a work-around for the "True Retention by Card Maturity" interference, but until then I believe it works with the regular "True Retention" add-on.  In your collections.media folder, do you have a folder called "pokemon_images"?

**Comment by galantra** [comment]
No, there are no folders. Only files.

**Comment by sivenchinniah** [comment]
Interesting, if you try updating the add-on, are there still no images?

**Comment by galantra** [comment]
![grafik](https://user-images.githubusercontent.com/52420923/67266242-08c41380-f4b0-11e9-938f-4f1a33366d50.png)
Sweeet!
