### ISSUE TITLE
Tools -> Check Media -> delete unused files: this deletes Pokemanki progress

### ISSUE THREAD

**Issue by Hudziak68** [sivenchinniah/Pokemanki#3]
It seems like when I do the steps above, my Pokemanki progress restarts. Is there a way to delete unused files without interfering with Pokemanki?

**Comment by sivenchinniah** [comment]
So Pokemanki stores the json file with your Pokemon in the collections.media folder.  What I would recommend doing if you want to delete unused files is to copy that file from that folder and then paste it back in after you delete unused files

**Comment by Hudziak68** [comment]
That's a good idea. Thank you very much!

**Comment by lizyn** [comment]
By prepending a  "_" to the filename, e.g. by renaming `pokemanki.json` to `_pokemanki.json`, Anki is told not to treat that particular file as unused. Of course, the filenames used in codes have to be changed accordingly. It seems that some addons I'm using adopted this method, such as _Fast Word Query_. I am not familiar with Anki addon development, just suggesting a possible solution here.

**Comment by lizyn** [comment]
Sorry if I sounds a bit nit-picking: according to the warning message blow, it's relatively not a good idea to use subfolders in `collection.media` folder, for which I think Anki is referring to the `progress_bars` & `pokemon_images` folders. 

<img width="500" alt="image" src="https://user-images.githubusercontent.com/26119970/69530484-112ad500-0fad-11ea-9c91-deb678cea209.png">

**Comment by sivenchinniah** [comment]
> By prepending a "_" to the filename, e.g. by renaming `pokemanki.json` to `_pokemanki.json`, Anki is told not to treat that particular file as unused. Of course, the filenames used in codes have to be changed accordingly. It seems that some addons I'm using adopted this method, such as _Fast Word Query_. I am not familiar with Anki addon development, just suggesting a possible solution here.

Thanks for letting me know! I didn't realize that was a thing, I'll add it to the code!

> Sorry if I sounds a bit nit-picking: according to the warning message blow, it's relatively not a good idea to use subfolders in `collection.media` folder, for which I think Anki is referring to the `progress_bars` & `pokemon_images` folders.
> 
> <img alt="image" width="500" src="https://user-images.githubusercontent.com/26119970/69530484-112ad500-0fad-11ea-9c91-deb678cea209.png">

No that's not nitpicky at all! I think the warning message is more for if you use the media in subfolders of the collection.media folder as actual cards, I think it's okay for add-on purposes
