### ISSUE TITLE
AttributeError: module 'aqt.gui_hooks' has no attribute 'stats_dialog_will_show'

### ISSUE THREAD

**Issue by sethb3744** [sivenchinniah/Pokemanki#35]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.23 (de9543ff) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.7
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-02-25 03:27:17
Add-ons possibly involved: ⁨Pokemanki⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/main.py", line 248, in onOpenProfile
  File "aqt/main.py", line 370, in loadProfile
  File "aqt/gui_hooks.py", line 1275, in __call__
  File "/Users/sethberg/Library/Application Support/Anki2/addons21/633922407/__init__.py", line 20, in startup
    from . import main
  File "/Users/sethberg/Library/Application Support/Anki2/addons21/633922407/main.py", line 136, in <module>
    gui_hooks.stats_dialog_will_show.append(onStatsOpen)
AttributeError: module 'aqt.gui_hooks' has no attribute 'stats_dialog_will_show'

**Comment by sivenchinniah** [comment]
Apologies, I put the wrong version of Anki as the cutoff for the new Pokemanki.  The change with the "gui_hooks" module was added to the newer versions of Anki.  I changed the cutoff to include Anki 2.1.23 in the older version of the add-on, let me know if that works!

**Comment by sethb3744** [comment]
That worked, thank you!
