### ISSUE TITLE
2.1.45 alpha 1 -> add-on broken 

### ISSUE THREAD

**Issue by NamelessGO** [sivenchinniah/Pokemanki#46]
![image](https://user-images.githubusercontent.com/66227691/118552277-b949d600-b72c-11eb-8857-7ea5bda2d17a.png)
https://www.reddit.com/r/Anki/comments/neoihx/anki_2145_alpha/ (changelogs)

**Comment by BlueGreenMagick** [comment]
I think this is fixed in non-alpha 2.1.45
