### ISSUE TITLE
[Question] Progression algorithm

### ISSUE THREAD

**Issue by zoenglinghou** [sivenchinniah/Pokemanki#6]
Thanks for making this awesome add-on.

I have a question regarding the progression of the Pokemons. So I have three decks, and I rarely go over two of them, while frequenting the other. However, the former have pokemons of a dozens level higher than that of the latter (and seems to progress a lot faster but I haven't use the add-on enough to verify).

Is it due to Anki's own algorithm or design choices of the add-on? Much appreciated.

**Comment by lizyn** [comment]
The level is computed based on average intervals of cards in the corresponding deck. You can see the details at [the addon page](https://ankiweb.net/shared/info/633922407) in a reply by the author made on 2019/10/10. Try searching for the keyword "intervals" at that page to locate it. 

So basically if you have a deck with fewer cards, you're likely to go over the whole deck in a shorter time cycle, i.e. increasing the average interval faster, along with the Pokémon level.

**Comment by zoenglinghou** [comment]
@lizyn interesting read, thanks! It is an interesting mechanic. I am also experiencing loss of levels because I have been adding card to a deck :(
